version: '3'

services:

  server:
    environment:
      DB_DSN: postgres://postgres:postgres@postgres/postgres
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports: 
      - 3000:3000
    volumes:
      - ./conduktor:/app/conduktor
    networks:
      - overlay

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - db:/var/lib/postgresql
    networks:
      - overlay

volumes:
  db:

networks:
  overlay: