version: '3'

services:

  server:
    environment:
      GOOGLE_OAUTH_CLIENT_ID: ${CONDUKTOR_GOOGLE_OAUTH_CLIENT_ID}
      AUTHORIZED_DOMAINS: ${CONDUKTOR_AUTHORIZED_DOMAINS}
    build:
      context: .
      dockerfile: ./docker/Dockerfile.build
      args:
        API_URL: ${CONDUKTOR_API_URL}
        BASE_URL: ${CONDUKTOR_BASE_URL}
        AUTHORIZED_DOMAINS: ${CONDUKTOR_AUTHORIZED_DOMAINS}
        GOOGLE_OAUTH_CLIENT_ID: ${CONDUKTOR_GOOGLE_OAUTH_CLIENT_ID}
        APP_TITLE: ${CONDUKTOR_APP_TITLE}
    volumes:
      - ./dist:/app/dist
    command:
      - /bin/bash
      - -c
      - "python setup.py sdist"
